[paths]
data_dir = "tests/mock_data"
generated_dir = "tests/generated"
images_dir = "tests/mock_data/images"
ground_truth_brutos_dir = "tests/mock_data/ground_truth_brutos"
segmentacoes_brutas_dir = "tests/generated/segmentacoes_brutas"
segmentacoes_binarizadas_dir = "tests/generated/segmentacoes_binarizadas"
ground_truth_binarizada_dir = "tests/generated/ground_truth_binarizada"
evaluation_dir = "tests/generated/evaluation"
indice_file = "tests/mock_data/Indice.xlsx"
sqlite_file = "tests/mock_generated/bufalos-testes.sqlite3"

[execution]
num_execucoes = 3

[analysis.segmentacao_binarizada]
execucao_escolhida = 1

[binarization]
ground_truth_strategy = "GaussianaOpeningBaixa"
segmentacao_strategies = [
    "GaussianaOpeningBaixa",
    "GaussianaOpeningAlta",
    "LimiarFixoBaixa",
    "LimiarFixoAlta",
    "OtsuOpeningBaixa",
    "OtsuOpeningAlta",
    "HistereseClosingBaixa",
    "HistereseClosingAlta",
]

[models]
u2netp = "cpu"

[evaluation.parallelism]
enabled = false
executor = "process"
max_workers = 1
batch_size = 4
