[paths]
data_dir = "tests/mock_data"
generated_dir = "tests/generated"
images_dir = "tests/mock_data/images"
ground_truth_raw_dir = "tests/mock_data/ground_truth_raw"
predicted_masks_dir = "tests/generated/predicted_masks"
predicted_masks_binary_dir = "tests/generated/predicted_masks_binary"
ground_truth_binary_dir = "tests/generated/ground_truth_binary"
evaluation_dir = "tests/generated/evaluation"
indice_file = "tests/mock_data/Indice.xlsx"
sqlite_file = "tests/mock_generated/bufalos-testes.sqlite3"

[models]
u2netp = "cpu"
